### ISSUE TITLE
Coordinates not resolved for some TOIs

### ISSUE THREAD

**Issue by Nschanche** [lightkurve/lksearch#26]
Some TOI and KOIs are not being resolved. For example, searching for TOI-4441 produces the error

`NameResolveError: Unable to find coordinates for name 'TOI 4441' using https://cds.unistra.fr/cgi-bin/nph-sesame/A?TOI%204441`

This happens when searching with TESSSearch or MASTSearch. From a handful of search tests, this seems to be the case only for TOIs not yet confirmed as planets. 

A workaround is to search by alternative names such as TIC ID, which does resolve the object. However, I would expect that TOI names should be able to produce search results.

**Comment by tylerapritchard** [comment]
This looks like its because when detect a user-defined string as 'target' input to the search class, we use `SkyCoord.from_name()`to create a SkyCoord Object from the target name prior to passing the user defined target string to `~astroquery.mast.Observations.query_criteria` for catalog search.  

It looks like `SkyCoord.from_name()` uses vizier which is not able to resolve the TOI while `Observations.query_criteria()` can.  

We have the Skycoord parsing in there so that Mastsearch.skycoord property has a valid result whether or not the user has passed a skycoord.  

`astroquery.MastClass().resolve_object()` returns a Skycoord and can resolve TOIs (and probably uses the same resolver as `Observations.query_criteria`?).  

I think we can either:
1. Swap `Skycoord.from_name` with `Mastclass().resolve_target()` to hopefully have a more uniform name resolver between the property and search.  
2. Remove the SkyCoord property - and assosciated code since we can't guarantee the resolving will be identical.  
3. Use the `astroquery.MastClass` resolver and then pass the resolved skycoord coordinates instead of the target string to `Observations.query_criteria`

What do you think?
